<a href="https://colab.research.google.com/github/Saifullah785/python-data-science-handbook-notes/blob/main/02_03_Computation_on_arrays_ufuncs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Ten-point summary highlighting the key concepts demonstrated in notebook on NumPy Universal Functions (ufuncs):**

**Problem:**

Standard Python loops are slow for element-wise array computations.

**Solution:**

NumPy provides Universal Functions (ufuncs) for fast, vectorized operations.

**What are Ufuncs?**

Functions operating element-by-element on arrays, implemented efficiently in compiled code.

**Performance:**

Ufuncs significantly outperform Python loops by avoiding Python-level overhead.

**Analogy:**

Think of loops as a single worker and ufuncs as an assembly line.

**Basic Operations:**

Ufuncs cover standard arithmetic (+, -, *, /), absolute value, and more, often accessible via operators.

**Mathematical Functions:**

Ufuncs provide efficient ways to compute trigonometric, exponential, and logarithmic functions on entire arrays.

**Specialized Functions:**

SciPy's special module offers more advanced mathematical ufuncs (e.g., gamma, error functions).

**Advanced Features:**

Ufuncs support features like specifying output arrays (out) for in-place operations.

**Array Methods:**

Ufuncs also have methods (reduce, accumulate, outer) for aggregation and outer products across array dimensions.

# **Computation on NumPy Arrays: Universal Functions**

Introduces the concept of Universal Functions (ufuncs) in NumPy as a way to perform fast, element-wise operations on arrays.


**The Slowness of Loops**

Demonstrates the performance limitations of standard Python loops when performing computations on large arrays.

In [2]:
# Define a function to compute reciprocals using a standard Python loop

import numpy as np
rng = np.random.default_rng(seed=1701)

def compute_reciprocals(values):
    output = np.empty(len(values))

    # Loop through each element and compute its reciprocal
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

# Create a small array of integers
values = rng.integers(1, 10, size=5)

# Compute reciprocals using the loop function and print the result
compute_reciprocals(values)

array([0.11111111, 0.25      , 1.        , 0.33333333, 0.125     ])

In [5]:
values

array([9, 4, 1, 3, 8])

In [3]:
# Create a large array for performance testing

big_array = rng.integers(1, 100, size=1000000)

# Measure the time it takes to compute reciprocals using the loop function

%timeit compute_reciprocals(big_array)

2.21 s ± 280 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
big_array

array([67, 40, 16, ..., 64, 26, 61])

# **Introducing Ufuncs**

Shows how ufuncs provide a vectorized and significantly faster alternative to explicit loops for array operations.

In [4]:
# Print the result of the loop-based reciprocal calculation for comparison

print(compute_reciprocals(values))

# Compute reciprocals using a NumPy ufunc (vectorized operation) and print the result

print(1.0 / values)

[0.11111111 0.25       1.         0.33333333 0.125     ]
[0.11111111 0.25       1.         0.33333333 0.125     ]


In [6]:
# Measure the time it takes to compute reciprocals using the NumPy ufunc

%timeit (1.0 / big_array)

2.08 ms ± 61.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
# Example of performing element-wise division between two NumPy arrays using a ufunc

np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [9]:
# Example of performing element-wise exponentiation using a ufunc

x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [10]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# **Exploring NumPy's Ufuncs**

Provides an overview of the various types of ufuncs available in NumPy for different mathematical and logical operations.

**Array Arithmetic**

Covers the basic arithmetic operations that can be performed efficiently on NumPy arrays using ufuncs.

In [11]:
# Create a NumPy array for arithmetic examples

x = np.arange(4)
print("x      =", x)
print("x + 5  =", x + 5)
print("x - 5  =", x - 5)
print("x * 2  =", x * 2)
print("x / 2  =", x / 2)
print("x // 2 =", x // 2)  # floor division

x      = [0 1 2 3]
x + 5  = [5 6 7 8]
x - 5  = [-5 -4 -3 -2]
x * 2  = [0 2 4 6]
x / 2  = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [12]:
x

array([0, 1, 2, 3])

In [13]:
# Perform and print more element-wise arithmetic operations

print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [14]:
# Example of a compound arithmetic operation using ufuncs

-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [15]:
# Example of using the explicit ufunc function for addition

np.add(x, 2)

array([2, 3, 4, 5])

# **✅ Equivalents of arithmetic operators:**

Presents a table mapping standard Python arithmetic operators to their corresponding NumPy ufuncs.

| Python Op | NumPy ufunc         | Example        |
| --------- | ------------------- | -------------- |
| `+`       | `np.add(x, y)`      | `np.add(x, 2)` |
| `-`       | `np.subtract(x, y)` | `x - 3`        |
| `*`       | `np.multiply(x, y)` | `x * 5`        |
| `/`       | `np.divide(x, y)`   | `x / 2`        |
| `//`      | `np.floor_divide()` | `x // 2`       |
| `**`      | `np.power()`        | `x ** 3`       |
| `%`       | `np.mod()`          | `x % 2`        |


# **Absolute Value**

Explains how to calculate the absolute value of elements in an array using NumPy's ufuncs.

In [16]:
# Create a NumPy array with positive and negative numbers

x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [17]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [18]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [19]:
# Compute the absolute value of complex numbers using np.abs()

x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

# **Trigonometric Functions**

 Shows how to apply trigonometric functions (like sin, cos, tan) to array elements using NumPy ufuncs.

In [20]:
# Create an array of angles in radians

theta = np.linspace(0, np.pi, 3)

In [21]:
# Compute and print the sine, cosine, and tangent of the angles using NumPy ufuncs

print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [22]:
# Create an array for inverse trigonometric functions

x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


# **Exponents and Logarithms**

Demonstrates the use of ufuncs for exponential and logarithmic calculations on array elements.

In [23]:
# Create an array for exponential examples

x = [1, 2, 3]
print("x   =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3., x))

x   = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3.  9. 27.]


In [24]:
# Create an array for logarithmic examples

x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [25]:
# Create an array for specialized exponential and logarithmic functions

x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


# **Specialized Ufuncs**

 Introduces ufuncs from the scipy.special module for more advanced mathematical functions

In [26]:
# Import the special module from SciPy

from scipy import special

In [27]:
# Gamma functions (generalized factorials) and related functions

# Create an array for gamma and beta function examples

x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


In [28]:
# Error function (integral of Gaussian),
# its complement, and its inverse

# Create an array for error function examples

x = np.array([0, 0.3, 0.7, 1.0])

# Compute and print the error function, complementary error function, and inverse error function using SciPy's special ufuncs

print("erf(x)  =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

erf(x)  = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


# **Advanced Ufunc Features**

 Explores some of the more advanced capabilities of ufuncs beyond basic element-wise operations.

**Specifying Output**

Shows how to use the out argument in ufuncs to specify where the results of an operation should be stored.

In [29]:
# Create an input array
# Create an empty output array of the same size
# Perform element-wise multiplication and store the result directly in the output array 'y'
# Print the output array

x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [30]:
# Create an output array with more elements
# Perform element-wise power operation and store the result in specific indices of the output array
# Print the output array

y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


**Aggregations**

Explains how ufuncs can be used to perform aggregation operations (like sum and product) on arrays.

In [31]:
# Create an array for aggregation examples

x = np.arange(1, 6)

# Compute the sum of all elements using the reduce method of the add ufunc

np.add.reduce(x)

np.int64(15)

In [32]:
# Compute the product of all elements using the reduce method of the multiply ufunc

np.multiply.reduce(x)

np.int64(120)

In [33]:
# Compute the cumulative sum of elements using the accumulate method of the add ufunc

np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [34]:
# Compute the cumulative product of elements using the accumulate method of the multiply ufunc

np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

**Outer Products**

Demonstrates how to compute the outer product of two arrays using ufuncs.

In [35]:
# Create an array for the outer product example
x = np.arange(1, 6)

# Compute the outer product of the array with itself using the outer method of the multiply ufunc

np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])